### ISSUE TITLE
readme for langtags

### ISSUE THREAD

**Issue by hatton** [silnrsi/sldr#13]
It would be super helpful if the `langtags` directory contained a README file explaining what each field means, what the source of this data is, how updates are created and when, etc.  

In my code, I wanted to document, precisely, what the `tag`  is. I assume it is  IETF BCP 47, but it feels sloppy to have to assume that, rather than point to some documentation.

**Comment by hatton** [comment]
Aha, just found some documentation under `doc` (unfortunate, I think;  I would have found it if it were in the same directly as the data).   But I did not see in that documentation the kind of thing I'm needing, so I'll leave this as a request for expansion, assuming relocation isn't likely.

**Comment by mhosken** [comment]
The documentation for language.json may be found in the source repo for
langtags, here:
https://github.com/silnrsi/langtags/blob/master/doc/langtags.md
Yes that is really quirky and I'm trying to think through the question of
what should go where. We may move langtags.json as a result.

GB,
Martin

**Comment by hatton** [comment]
Thanks Martin. From that document:

> tag The canonical tag for this set.
> full: The full tag for this set
> tags: A list of other tags that are equivalent

Perhaps because this isn't my field of expertise, I need definitions that area lot more formal. E.g. could you name standard that each field adheres to?

> names: Other alternative names for this language coming from the Ethnologue names list, including alternate names and names and alternate names from other regions.

It would be helpful to state whether  pejorative names included.

thanks!

**Comment by mhosken** [comment]
Dear John,

All the tags conform to BCP47. That's what makes them a tag (short for
language tag). I agree I could unpack canonical a bit better. Basically,
use the tag field for the langtag you want to output. Use the full field if
you want to unpack it and use the tags list for other tags that are
equivalent, but that you would not want to output.

As stated in the readme for the project, every effort is expended to ensure
there are no prejorative names anywhere.

HTH,
GB,
Martin
