### ISSUE TITLE
con.* is an issue on Windows

### ISSUE THREAD

**Issue by LornaSIL** [silnrsi/sldr#16]
The file `con.xml` was renamed to `con_Latn.xml`.

However, `con.tsv` also needs renaming (https://github.com/silnrsi/sldr/blob/master/gclusters/c/con.tsv)

I am still unable to clone the repo on a Windows machine as `con` has special meaning to Windows.

**Comment by srl295** [comment]
ref: https://unicode-org.atlassian.net/browse/CLDR-15077

**Comment by srl295** [comment]
@LornaSIL looks like this was done in https://github.com/silnrsi/sldr/commit/51ecd5e18695798ecbd93e9bda1a1b722fee488d
