### ISSUE TITLE
ngb exemplar characters seem to be missing vowels with tilde or acute

### ISSUE THREAD

**Issue by moyogo** [silnrsi/sldr#19]
The ngb locale data has the following main character exemplar:

https://github.com/silnrsi/sldr/blob/6c4fb98a84b9eb1326b59ba6a3d7be8b76d40dcc/sldr/n/ngb.xml#L20

But the [Fana Ngbangɔ 1987](https://www.bible.com/versions/2682) (New Testament translation) by the Bible Society of the Democratic Republic of Congo seems to using the combining tilde on nasal vowels, for example:
- ã in *akpã*
- ẽ in *ndẽ*
- {ɛ̃} in *ndɛ̃*
- ĩ in *sĩni*
- {ɔ̃} in *nzɔ̃*
- ũ in *hũngɔ*

The acute accent is also used in some words:
- á in *kwá*
- é in *sé*
- {ɛ́} in *tɛ́nɛ*
- í in *ahí*
- ó in *ló*
- ú in *adú*

I may have missed a couple.

**Comment by DavidLRowe** [comment]
\u0301 and \u0303 added to main exemplar (https://github.com/silnrsi/sldr/commit/ec221476e12056b125bdb8914f55a88e7c27e38f)

Thanks!
