### ISSUE TITLE
Add case tailoring information

### ISSUE THREAD

**Issue by mhosken** [silnrsi/sldr#22]
Add a way to describe case tailoring for this locale. Currently there are only 4 localised lower casings: el, lt, tr, az:
- el has special final sigma handling to final sigma
- lt has dotless i handling also with support for U+0300, U+0301, U+0303, U+0307, U+0328
- tr has dotless i handling
- az is the same as tr
The reason for marking associations is that ICU, for example, does not use transforms to do its lower case tailoring. Instead it just checks the locale for one of the small list it knows about. Therefore, rather than specifying a specific tailoring, it is easier to just specify an alternative locale that this locale has the same case tailoring. A simple @alias can be used to specify the locale to use.

But it may be that none of the existing locales adequately reflects the case tailoring. Thus we would want to refer to a specific transform file. But there are 3 casings that a tailoring has to specify: lower, upper, title. SIL LDML already has a mechanism for referencing transforms and this is used here. Instead of an @alias, we use @transform which specifies @from for an sil:transform element. The @to for this attribute will be `-Lower`, `-Upper`, or `-Title` according to the required output folding.

Where to put this thing? It stands alone and seems overkill for it to have its own top level special element. We can therefore add to sil:external-resources. Let's call it sil:case-tailoring.

**Comment by papeh** [comment]
Required for https://jira.sil.org/browse/LT-20816
