### ISSUE TITLE
brh.xml missing closing </characters> tag

### ISSUE THREAD

**Issue by colinmford** [silnrsi/sldr#26]
PR #25 fixes the following error returned by `lxml` when parsing [brh.xml](https://github.com/silnrsi/sldr/blob/760a5eb544bd51756b3dd95f9e665ee7e19099f3/sldr/b/brh.xml).

```
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: characters line 29 and ldml, line 45, column 8
```

**Comment by DavidLRowe** [comment]
Thank you!
