### ISSUE TITLE
Northern Dagara [dgi] exemplarCharacters issues

### ISSUE THREAD

**Issue by moyogo** [silnrsi/sldr#28]
The Northern Dagara [dgi] exemplarCharacters has issues:
```xml
<exemplarCharacters>[a b ɓ c d e ɛ f g {gb} h ɦ i ɩ j k {kp} l {ˀl} m n {ñ} ŋ {ŋm} o ɔ p r ɾ s t u ʋ v w {ˀw} y ƴ z ˀ]</exemplarCharacters>
```

It’s not clear where these come from but based on [Joachim D. Somé, "Dagara Orthography", *Journal of Dagaare Studies*, vol. 4,‎ 2004](https://web.archive.org/web/20060512162902/http://www.hku.hk/linguist/staff/Bodomo/JDS/2004/JDS2004_Some.pdf)
- `ɦ {ˀl} {ˀw} ˀ` should be `{ʼh} {ʼl} {ʼw} ʼ`
- `ɾ` should be removed.
- the tone marking and nasalization of vowels`à è {ɛ̀} ì {ɩ̀} ò {ɔ̀} ù {ʋ̀} á é {ɛ́} í {ɩ́} ó {ɔ́} ú {ʋ́} ã ẽ {ɛ̃} ĩ {ɩ̃} õ {ɔ̃} ũ {ʋ̃}` should be added and the stacked diacritics `{ã̀} {ẽ̀} {ɛ̃̀} {ĩ̀} {ɩ̃̀} {õ̀} {ɔ̃̀} {ũ̀} {ʋ̃̀} {ã́} {ẽ́} {ɛ̃́} {ĩ́} {ɩ̃́} ṍ {ɔ̃́} {ṹ} {ʋ̃́}` likely as well.

This seems to correspond with the characters used in [*A Sɛb-Sõw*](https://www.bible.com/bible/3053/GEN.1.DBDC), Alliance Biblique du Burkina Faso, 2013. Although only of the stacked diacritics `{ã́}` seems to appear.

**Comment by emily-roth** [comment]
Thank you so much for raising this issue!

It seems like the incorrect information comes from [Alphabets of Africa](https://www.sil.org/resources/archives/5133), by Rhonda Hartell (1993), page 43 (or 53 in the PDF reader). It makes sense that a 30-year-old text would have some outdated information, though it's still a useful starting point for research. 

I updated the file in the SLDR accordingly and it should be reflected in the master branch of the repo at this point. It'll update everywhere else when we do our next release of the SLDR, which should hopefully be sometime this coming November/December. Thank you again!
