### ISSUE TITLE
Bassa [bsq_Latn] exemplar characters issues

### ISSUE THREAD

**Issue by moyogo** [silnrsi/sldr#30]
Bassa [bsq_Latn] exemplar characters is a follows:
```
[a b ɓ {č} d ɖ e ɛ f g {gb} h i j k {kp} m n {ny} o ɔ p s t u v w]
```

Based on [*Bassa-English Dictionary*, Christian Education Foundation in Liberia (CEFL)](https://cefliberia.org/bassa/bassa-dictionary/) and [*Ɓǎsɔ́ɔ̀ Báɓòɔ̀*, Bible Society Liberia, 2002](https://www.bible.com/versions/2826?returnTo=MAT.1).
The issues are:
- `{č}` should be `c`
- nasalized vowels (a ɛ i ɔ u with tilde) or tone marked vowels (a e ɛ i o ɔ u with acute, grave, caron), as well as combinations of both, are missing.

**Comment by emily-roth** [comment]
Thank you so much for raising this issue! You're completely right. Funnily enough, this is the only one of the issues you raised where I never stumbled upon the origin of the mistake along the way. I updated the file in the SLDR accordingly and it should be reflected in the master branch of the repo at this point. It'll update everywhere else when we do our next release of the SLDR, which should hopefully be sometime this coming November/December. Thank you again!
