### ISSUE TITLE
What should I do to improve Russian translations?

### ISSUE THREAD

**Issue by Mercury13** [silnrsi/sldr#31]
What I see for now…
Osma: османская → османья (сомалийская)
Lepc: лепха → лепча
Hung: старовенгерская → венгерские руны (just better)
Hans: упрощенная китайская → упрощённая китайская (just better)
Bugi: бугинизийская → бугийская (лонтара)
Sgnw: язык знаков → жестовое письмо Саттон
Phli: пахлави псалтирная → псалтырское пехлеви
Dsrt: дезерет → дезеретская (мормонская) (just better)
Lyci: лициан → ликийская
Jamo: джамо → корейские чамо
Hano: хануну → хануноо
Plrd: поллардовская фонетика → мяо (письмо Полларда)
Hani: китайская → ККЯ иероглифы (not just Chinese)
Hanb: ханьб → китайская и бопомофо
Palm: пальмиры → пальмирская
Moon: азбука муна → шрифт Муна
Syrn: восточно-сирийская → восточносирийская
Qaag: зоджи → бирманский шрифт Zawgyi
Runr: руническая → руны (just better)

**Comment by mhosken** [comment]
Thank you for getting in contact.

For majority languages, the SLDR gets its data from the CLDR. We do not
make changes (only additions) to those language data sets. If you would
like to see these values changed, you will need to get them changed by CLDR
and go through their voting process.
