### ISSUE TITLE
Dumi language: Why the U+0621: ARABIC LETTER HAMZA?

### ISSUE THREAD

**Issue by madig** [silnrsi/sldr#41]
See https://github.com/silnrsi/sldr/blob/f452bb9e5089c6871af30b0552a3a71b0879b72b/sldr/d/dus.xml#L24.

Should `\u0621` have been `\u0921`?

**Comment by emily-roth** [comment]
Ha! By the looks of it, it's a 6-year-old typo. Thanks for catching it!

**Comment by Hoolean** [comment]
Thanks for confirming and fixing, Emily!

We weren't totally sure ourselves so thought it best to check, as [Omniglot says that Dumi has a glottal stop but no Dda](https://www.omniglot.com/writing/dumi.htm), and [Wikipedia says that Hamza denotes a glottal stop](https://en.wikipedia.org/wiki/Hamza) (at least, in the context of the Arabic alphabet), but the ordering and sequence makes the typo above look very likely so the former may just be a spooky coincidence :)
