### ISSUE TITLE
Incorrect inclution of script tags?

### ISSUE THREAD

**Issue by hatton** [silnrsi/sldr#6]
I'm told that alltags is the root of what we're seeing:
![image](https://user-images.githubusercontent.com/8448/54403408-8364bf00-4695-11e9-947a-d934e8bd25d9.png)

This is a critical problem holding up our release.

**Comment by mhosken** [comment]
I have updated the list to remove the seemingly redundant script tag from those langtags and all those from clearly Latin script areas, including Nigeria. I've taken a bit of a risk with that one. Hopefully it won't come back to bite us. A new version of the data can be found in https://github.com/silnrsi/sldr/blob/master/extras/langtags.json

Please be aware that tags are liable to change. This is an example of that. There are many more tags that will probably have their script component removed once we have checked them with experts.
