### ISSUE TITLE
langtags.json has bogus entries

### ISSUE THREAD

**Issue by jasonleenaylor** [silnrsi/sldr#8]
two entries at the top look suspicious:
``{
        "tag": "_globalvar", 
        "variants": [ "simple" ]
    }, 
    {
        "tag": "_phonvar", 
        "variants": [ "alalc97", "fonipa", "fonkirsh", "fonnapa", "fonupa", "fonxsamp" ]
    }, ``

**Comment by mhosken** [comment]
There are two 'magic' tags that hold extra information. Please see docs/langtags.md in the langtags repo for details.
