### ISSUE TITLE
downloaded langtags.json has 4 bad iso639_3 fields

### ISSUE THREAD

**Issue by StephenMcConnel** [silnrsi/sldr#9]
The downloaded langtags.json file consistently has the following four entries with totally bogus iso639_3 fields.  The URL was "https://ldml.api.sil.org/index.html?query=langtags&ext=json"
...
    {
        "full": "szy-Zyyy-TW", 
        "iso639_3": "30-Jan-2019", 
        "name": "Sakizaya", 
        "region": "TW", 
        "regionname": "Taiwan, Province of China", 
        "sldr": false, 
        "tag": "szy", 
        "tags": [ "szy-TW", "szy-Zyyy" ]
    }, 
...
    {
        "full": "tjj-Latn-AU", 
        "iso639_3": "28-Jan-2019", 
        "name": "Tjungundji", 
        "region": "AU", 
        "regionname": "Australia", 
        "sldr": false, 
        "tag": "tjj", 
        "tags": [ "tjj-AU", "tjj-Latn" ]
    }, 
...
    {
        "full": "tjp-Latn-AU", 
        "iso639_3": "28-Jan-2019", 
        "name": "Tjupany", 
        "region": "AU", 
        "regionname": "Australia", 
        "sldr": false, 
        "tag": "tjp", 
        "tags": [ "tjp-AU", "tjp-Latn" ]
    }, 
...
    {
        "full": "wkr-Latn-AU", 
        "iso639_3": "28-Jan-2019", 
        "name": "Keerray-Woorroong", 
        "region": "AU", 
        "regionname": "Australia", 
        "sldr": false, 
        "tag": "wkr", 
        "tags": [ "wkr-AU", "wkr-Latn" ]
    }, 
...

**Comment by LornaSIL** [comment]
I'm pretty sure these were all added in January to 639-3.

**Comment by StephenMcConnel** [comment]
Why was this issue closed without being fixed???  The same thing is still happening today.

**Comment by mhosken** [comment]
Because it was misread. But it is fixed now.
